### ISSUE TITLE
Horde.Supervisor.start_child returns nil pid when :already_started

### ISSUE THREAD

**Issue by xadhoom** [derekkraan/horde#102]
When starting a new child with `Horde.Supervisor.start_child/2` and the child is already started, the error `{:error, {:already_started, pid}}` is returned, but pid is always nil.

Having the pid in the returned error is commonly used to perform operation on the process, for example try to start the process -> already started -> GenServer.call(pid, whatever).

**Comment by derekkraan** [comment]
Also fixed by #122.
