### ISSUE TITLE
Improve module based supervisor

### ISSUE THREAD

**Issue by xadhoom** [derekkraan/horde#107]
Current module based supervisor implementation does not allow setting supervisor options like max restarts, timers and so on, that's because of:

* child_spec is not overridable
* init/1 in standard module-based supervisor is expected to return a Supervisor.init call, in horde returns some options that's not clear what are used for

My suggestion is to make the module-based supervisor as the standard one. If is too complicated maybe make child_spec overridable in the macro?

**Comment by derekkraan** [comment]
If you define `child_spec/1` on your supervisor, and then use `MySupervisor` as a child somewhere, then `MySupervisor.child_spec` will be used. There are no changes necessary in Horde for this.

The `init/1` callback works like [DynamicSupervisor.init/1](https://hexdocs.pm/elixir/DynamicSupervisor.html#init/1). Perhaps the documentation could be improved.

Perhaps you could show me what you'd like to do with your module-based supervisor, and we can see what would be necessary to support that?

Derek

**Comment by xadhoom** [comment]
> If you define `child_spec/1` on your supervisor, and then use `MySupervisor` as a child somewhere, then `MySupervisor.child_spec` will be used. There are no changes necessary in Horde for this.

No, the compiler will warn that child_spec is already defined and will use the macro generated one, not the specified. Is just a matter of adding `defoverridable` into the macro itself.

About what to do, I'm just trying to pass [Supervisor options](https://hexdocs.pm/elixir/DynamicSupervisor.html#init/1-options) to the processes supervisor.

**Comment by derekkraan** [comment]
Ahh ok. If that's the case then I will accept a PR to add that to the macro + a test to show that it should be callable.

Sounds like that change will support your use case.

**Comment by derekkraan** [comment]
Will you submit a PR for this @xadhoom ?

**Comment by xadhoom** [comment]
Yes, but I cannot do it right now, a bit of hard work on the pipeline :)

**Comment by derekkraan** [comment]
No worries, if someone needs it, they'll do it ;)

**Comment by ordepdev** [comment]
I'll be happy to jump into this after figure out what I need to do 😅

**Comment by ordepdev** [comment]
Lets see if I understood correctly 🤔 

```elixir
defmacro __using__(_opts) do
    quote do
      @behaviour Horde.Supervisor

      def child_spec(options) do
        options = Keyword.put_new(options, :id, __MODULE__)

        %{
          id: Keyword.get(options, :id, __MODULE__),
          start: {__MODULE__, :start_link, [options]},
          type: :supervisor
        }
      end

      def start_link(options) do
        Horde.Supervisor.start_link(Keyword.put(options, :init_module, __MODULE__))
      end
    end
  end
```

Since the `HordeSupervisor` is defining a `child_spec` in the _macro_ that's not overridable, when I define a new _module based supervisor_ `TestSupervisor3` with a _custom_ `child_spec` as:

```elixir
defmodule TestSupervisor3 do
  use Horde.Supervisor

  @spec init(keyword) :: {:ok, [{atom, any}, ...]}
  def init(options) do
    {:ok, Keyword.put(options, :members, [:init_sup_test_3, :init_sup_test_3])}
  end

  def child_spec(args) do
    %{
      id: args[:id],
      start: {__MODULE__, :start_link, [args]},
      restart: :transient,
      type: :supervisor
    }
  end
end
```

I will get this warning message stating that my `child_spec` will not be used because it's using the one provided by `Horde.Supervisor`:

```
warning: this clause cannot match because a previous clause at line 18 always matches
  test/support/module_based_supervisor.ex:24
```

Am I right at this point? 😄

---

So, if I change the `Horde.Supervisor` to allow `child_spec` to be overridable as:

```elixir
defmacro __using__(opts) do
    quote do
      @behaviour Horde.Supervisor

      def child_spec(options) do
        options = Keyword.put_new(options, :id, __MODULE__)

        default = %{
          id: Keyword.get(options, :id, __MODULE__),
          start: {__MODULE__, :start_link, [options]},
          type: :supervisor
        }

        Supervisor.child_spec(default, unquote(Macro.escape(opts)))
      end

      def start_link(options) do
        Horde.Supervisor.start_link(Keyword.put(options, :init_module, __MODULE__))
      end

      defoverridable child_spec: 1
    end
  end
```

I'm now able to define and use the _custom_ `child_spec` in my `TestSupervisor3`!

What kind of test makes sense to add?

**Comment by derekkraan** [comment]
Looks like you've figured it out.

We test module based supervisors by defining a module based supervisor (in `test/support/module_based_supervisor.ex`) and then asserting on that in a test. You could do the same to test that you can override the child_spec.

**Comment by ordepdev** [comment]
Yeah, that's what I currently have:

```elixir
test "can use `child_spec` function to override defaults from Horde.Supervisor" do
  spec = %{
    id: 123,
    start:
      {TestSupervisor3, :start_link,
        [
          custom_id: 123,
          name: :init_sup_test_3,
          strategy: :one_for_one
        ]},
    restart: :transient,
    type: :supervisor
  }

  assert spec =
            TestSupervisor3.child_spec(
              custom_id: 123,
              name: :init_sup_test_3,
              strategy: :one_for_one
            )
end
```

My `TestSupervisor3` has a custom `child_spec` defined and it's respecting that. Is this what you had in mind? Assert their own `child_spec`? If yes, I'll open the PR right away 👍
