### ISSUE TITLE
Issues on joining/leaving hordes 

### ISSUE THREAD

**Issue by mszmurlo** [derekkraan/horde#11]
Hi,

Unless I misunderstood something, I believe there are some issues in
joining/leaving hordes. Below are the traces and comments on
experiment I have done so far. As all is about the same topic, I open just
one issue

For what follows I have a `XYZ.Utils` module with two helper functions that will be used later:

    def start_worker(name) do
      cs = %{id: name, start: {XYZ.Worker, :start_link, [[client_id: name]]}}
      Horde.Supervisor.start_child(XYZ.DSup, cs)
    end

    def lookup(name) do
     Horde.Registry.lookup(XYZ.Worker.via_tuple(name))
    end

and a `XYZ.Worker` module which is basically a `GenServer` with few
API that are not relevant here.

All examples start with a fresh situation with two nodes started with
`ERL_AFLAGS="-name nd1@127.0.0.1 -setcookie abcd" iex -S mix` and
`ERL_AFLAGS="-name nd2@127.0.0.1 -setcookie abcd" iex -S mix` in two
terminals. Then `nd1` connect to `nd2` with
`Node.connect(:"nd2@127.0.0.1")`.

## I1 : joining a horde on a node that does not exist

Joining the hordes from `nd1` to `nd2` works fine

    iex(nd1@127.0.0.1)1> Horde.Cluster.join_hordes(XYZ.DSup, {XYZ.DSup, :"nd2@127.0.0.1"})
    :ok
    iex(nd1@127.0.0.1)2> Horde.Cluster.join_hordes(XYZ.DReg, {XYZ.DReg, :"nd2@127.0.0.1"})
    :ok

However, the system returns `:ok` if you specify a node name that does not exist:

    iex(nd1@127.0.0.1)9> Horde.Cluster.join_hordes(XYZ.DReg, {XYZ.DReg, :"nd4@127.0.0.1"})
    :ok

Same holds for supervisors. Returning `false` would provide the same
semantics as `Node.connect()`.

## I2: Upon `leave_hordes()` registry on removed node is not cleaned properly

Start with a fresh situation, join the hordes and start a process
that will run on `nd1`. Check on both nodes that the process is available:

    iex(nd1@127.0.0.1)11> XYZ.Utils.lookup("a1")
    #PID<0.215.0>

and on `nd2`

    iex(nd2@127.0.0.1)5> XYZ.Utils.lookup("a1")
    #PID<18754.215.0>

Good. Now leave the horde on `nd2` and check for cluster members:

    iex(nd2@127.0.0.1)7> Horde.Cluster.leave_hordes(XYZ.DReg)
    :ok
    iex(nd2@127.0.0.1)8> Horde.Cluster.members(XYZ.DReg)
    {:ok,
     %{
       <<137, 122, 137, 240, 81, 186, 67, 134, 134, 190, 218, 93, 121, 158, 66, 210,
         155>> => {#PID<18754.173.0>, #PID<18754.176.0>}
     }}

and on `nd1`

    iex(nd1@127.0.0.1)13> Horde.Cluster.members(XYZ.DReg)
    {:ok,
     %{
       <<137, 122, 137, 240, 81, 186, 67, 134, 134, 190, 218, 93, 121, 158, 66, 210,
         155>> => {#PID<0.173.0>, #PID<0.176.0>}
     }}

This is ok. Yet, if we lookup the name  on `nd2` we still get the process pid:

    iex(nd2@127.0.0.1)11> XYZ.Utils.lookup("a1")
    #PID<18754.215.0>

Is it a wanted behaviour ? If so I would understand that the registry
on `nd2` keeps the processes that are running on `nd2`, but here the
process runs on the other node and this behaviour seems
inappropriate. Otherwise, it may imply the cleanup is not done on the
removed node.

NB: I understand CRDT are *eventually consistent*. I re-looked up
several times (after 10s, 30s and maybe 1mn) and the process is still
registered.

## I3: Node leaving a registry takes time

This is not really an  issue but more a remark: if one
registry is removed, say the one running on `nd2` as in the previous
example, sometimes (subjective measure...: between 10s to 30s of what
I could experiment) running `Horde.Cluster.members(XYZ.DReg)` on `nd2`
shows both registries for a while. I ran into this once then I had to
retry several times before getting it again. My system was CPU flat
and there was no process registered. I believe this is due to some
CRDT synchronizations, yet it seems long. What would happen if a
process is to be registered after the node had left a horde but before
everything is cleaned up?

## I4: Leaving a supervisor horde generates an error

`nd1` and `nd2` are freshly started and hordes are joined. Leaving the
 supervision horde on `nd2` seems to work fine:

    iex(nd2@127.0.0.1)4> Horde.Cluster.leave_hordes(XYZ.DSup)
    :ok

After a while, however, we get the following error:

    iex(nd2@127.0.0.1)5>
    2018-06-27 06:54:50.103 - pid=<0.164.0> [error] - GenServer XYZ.DSup terminating
    ** (stop) exited in: GenServer.stop(#PID<0.165.0>, :force_shutdown, :infinity)
        ** (EXIT) no process: the process is not alive or there's no process currently
          associated with the given name, possibly because its application isn't started
        (elixir) lib/gen_server.ex:789: GenServer.stop/3
        (horde) lib/horde/supervisor.ex:146: Horde.Supervisor.terminate/2
        (stdlib) gen_server.erl:648: :gen_server.try_terminate/3
        (stdlib) gen_server.erl:833: :gen_server.terminate/10
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
    Last message: :force_shutdown
    State: %Horde.Supervisor.State{distribution_strategy: Horde.UniformDistribution,
    members: %{<<27, 95, 41, 179, 113, 231, 211, 136, 166, 166, 226, 32, 200, 173, 190, 5, 62>> =>
      {:shutting_down, {#PID<0.164.0>, #PID<0.165.0>, #PID<0.166.0>, #PID<0.169.0>}},
      <<216, 132, 252, 114, 237, 23, 140, 220, 238, 8, 30, 25, 202, 105, 106, 195, 70>> =>
      {:alive, {#PID<15878.164.0>, #PID<15878.165.0>, #PID<15878.166.0>, #PID<15878.169.0>}}},
      members_pid: #PID<0.166.0>,
      node_id: <<27, 95, 41, 179, 113, 231, 211, 136, 166, 166, 226, 32, 200, 173, 190, 5, 62>>,
      processes: %{}, processes_pid: #PID<0.169.0>, processes_updated_at: 5,
      processes_updated_counter: 5, shutting_down: true, supervisor_pid: #PID<0.165.0>}

Again the systems load is flat and there is no process being supervised.
This may mean that leaving the horde take too long.

## I5: Leaving (the hard way) then re-joining of a registry horde fails

`nd1` and `nd2` are freshly started and registry hordes are
joined. No process is registered:

    iex(nd1@127.0.0.1)2>     Node.connect(:"nd2@127.0.0.1")
    true
    iex(nd1@127.0.0.1)3>     Horde.Cluster.join_hordes(XYZ.DReg, {XYZ.DReg, :"nd2@127.0.0.1"})
    :ok

When listing the members of the cluster on `nd1`, I get:

    iex(nd1@127.0.0.1)7> Horde.Cluster.members(XYZ.DReg)
    {:ok,
     %{
       <<83, 195, 54, 96, 102, 20, 156, 116, 131, 106, 17, 103, 11, 204, 251, 33,
         138>> => {#PID<15833.173.0>, #PID<15833.176.0>},
       <<189, 133, 217, 206, 174, 187, 181, 173, 175, 99, 162, 160, 87, 102, 179,
         153, 55>> => {#PID<0.173.0>, #PID<0.176.0>}
     }}

`<<83, 195, ...>>` is the part running on `nd2`.

OK. Now, let's kill `nd2` (with `Control-C`) and let's restart it and
re-join the registry horde:

iex(nd2@127.0.0.1)2>     Node.connect(:"nd1@127.0.0.1")
true
iex(nd2@127.0.0.1)3>     Horde.Cluster.join_hordes(XYZ.DReg, {XYZ.DReg, :"nd1@127.0.0.1"})
:ok

I get the following messages every 5 seconds on `nd2`, for ever:

    2018-06-29 06:27:35.825 - pid=<0.32.0> [error] - Discarding message
    {delta, {<0.176.0>,#{'__struct__'=>'Elixir.DeltaCrdt.CausalDotMap',causal_context=>
     #{'__struct__'=>'Elixir.DeltaCrdt.CausalContext',dots=>
     #{'__struct__'=>'Elixir.MapSet',map=>#{},version=>2},maxima=>#{}},keys=>#{'__struct__'=>
     'Elixir.MapSet',map=>#{},version=>2},state=>#{}}},1}
     from <0.176.0> to <0.176.0> in an old incarnation (1) of this node (2)

    2018-06-29 06:27:35.826 - pid=<0.32.0> [error] - Discarding message
    {delta,{<0.173.0>,#{'__struct__'=>'Elixir.DeltaCrdt.CausalDotMap',causal_context=>#{'__struct__'=>
    'Elixir.DeltaCrdt.CausalContext',dots=>#{'__struct__'=>'Elixir.MapSet',map=>#{{317600142,0}=>
    [],{376039348,0}=>[],{629303426,0}=>[]},version=>2},maxima=>#{317600142=>
    0,376039348=>0,629303426=>0}},keys=>#{'__struct__'=>'Elixir.MapSet',map=>
    #{<<83,195,54,96,102,20,156,116,131,106,17,103,11,204,251,33,138>>=>
    [],<<124,86,99,184,16,232,64,101,19,160,234,151,99,96,179,111,197>>=>
    [],<<189,133,217,206,174,187,181,173,175,99,162,160,87,102,179,153,55>>=>[]},version=>2},
    state=>#{<<83,195,54,96,102,20,156,116,131,106,17,103,11,204,251,33,138>>=>
    #{'__struct__'=>'Elixir.DeltaCrdt.CausalDotMap',causal_context=>nil,keys=>
    #{'__struct__'=>'Elixir.MapSet',map=>#{{{<0.173.0>,<0.176.0>},1530242807895109565}=>[]},version=>2},
    state=>#{{{<0.173.0>,<0.176.0>},1530242807895109565}=>#{'__struct__'=>
    'Elixir.DeltaCrdt.CausalDotSet',causal_context=>nil,state=>#{'__struct__'=>
    'Elixir.MapSet',map=>#{{317600142,0}=>[]},version=>2}}}},
    <<124,86,99,184,16,232,64,101,19,160,234,151,99,96,179,111,197>>=>
    #{'__struct__'=>'Elixir.DeltaCrdt.CausalDotMap',causal_context=>nil,keys=>
    #{'__struct__'=>'Elixir.MapSet',map=>#{{{<0.173.0>,<0.176.0>},1530242849488856679}=>[]},version=>2},
    state=>#{{{<0.173.0>,<0.176.0>},1530242849488856679}=>#{'__struct__'=>
    'Elixir.DeltaCrdt.CausalDotSet',causal_context=>#{'__struct__'=>
    'Elixir.DeltaCrdt.CausalContext',dots=>#{'__struct__'=>'Elixir.MapSet',map=>#{},version=>2},maxima=>#{}},
    state=>#{'__struct__'=>'Elixir.MapSet',map=>#{{376039348,0}=>[]},version=>2}}}},
    <<189,133,217,206,174,187,181,173,175,99,162,160,87,102,179,153,55>>=>
    #{'__struct__'=>'Elixir.DeltaCrdt.CausalDotMap',causal_context=>nil,keys=>
    #{'__struct__'=>'Elixir.MapSet',map=>#{{{<15833.173.0>,<15833.176.0>},
    1530242805313776549}=>[]},version=>2},
    state=>#{{{<15833.173.0>,<15833.176.0>},1530242805313776549}=>#{'__struct__'=>
    'Elixir.DeltaCrdt.CausalDotSet',causal_context=>nil,
    state=>#{'__struct__'=>'Elixir.MapSet',map=>#{{629303426,0}=>[]},version=>2}}}}}}},2}
    from <0.173.0> to <0.173.0> in an old incarnation (1) of this node (2)

If I check on `nd1` the list of members, I get:

    iex(nd1@127.0.0.1)8> Horde.Cluster.members(XYZ.DReg)
    {:ok,
     %{
       <<83, 195, 54, 96, 102, 20, 156, 116, 131, 106, 17, 103, 11, 204, 251, 33,
         138>> => {#PID<15833.173.0>, #PID<15833.176.0>},
       <<124, 86, 99, 184, 16, 232, 64, 101, 19, 160, 234, 151, 99, 96, 179, 111,
         197>> => {#PID<15833.173.0>, #PID<15833.176.0>},
       <<189, 133, 217, 206, 174, 187, 181, 173, 175, 99, 162, 160, 87, 102, 179,
         153, 55>> => {#PID<0.173.0>, #PID<0.176.0>}
     }}

`<<83, 195, ...>>` is still here and points to the processes on the
killed node. This shows that the old registry was not removed when
`nd2` was killed.

NB: I tried the same with supervisors which seem to work fine. The processes are restarted
on remaining nodes and while the reference of the old supervisor is
still present as well, it is labelled as `:dead`. Re-joining generates
no issue. By the way, I'm wondering why do you keep this information ?

If you need clarifications on this report, let me know.

Cheers

**Comment by derekkraan** [comment]
Hi, thanks for taking the time to test and report your findings here, this is valuable information to us.

I've taken a quick look at the first couple of issues:

I1. Good feedback, I'll change the semantics of `Horde.Cluster` to match `Node` as closely as possible. PR to follow.

I2. Registry is not cleaned after `Horde.Cluster.leave_hordes` - this is a tricky question. The purpose of providing a `leave_hordes` is to allow graceful shutdown of a particular node. The Supervisor removes all of its processes and shuts itself down after a time.

Actually I think the correct solution here is to remove `leave_hordes/1` and move this functionality to `Horde.Supervisor.stop/1` and `Horde.Registry.stop/1`. This will avoid confusion on the exact purpose of `leave_hordes` and allow me to clear up the differences between `stop` and `leave_hordes`.

I3. Node leaving a cluster should be very fast for Registry, and will take a while for Supervisor, depending on how long it takes the supervised processes to shut down. I'll take a look at this to see if there are some improvements that can be made.

I haven't got to I4 and I5 yet, I'll take a closer look at those when I've got I1-3 taken care of.

**Comment by derekkraan** [comment]
Hi @mszmurlo,

Could you take a look at #12 (branch: `fix_issues_cluster`) and see if this fixes your issues?

I haven't done anything about your fifth point yet because it doesn't affect the operation of `Horde`(?)

**Comment by mszmurlo** [comment]
Hi Derek,

I was away for a while and I had no really time to test.

I got branch `fix_issues_cluster` but now the initialization of my application itself fails. The application starts with


     ## in lib/xyz/application.ex
     def start(type, args) do
        Logger.debug("type=#{inspect type}, args=#{inspect args}")

        children = [
          {Horde.Supervisor, [name: XYZ.DSup, strategy: :one_for_one]},
          {Horde.Registry, keys: :unique, name: XYZ.DReg}
        ]
        opts = [strategy: :one_for_one, name: XYZ.AppSup]
        Supervisor.start_link(children, opts)
      end

and I get many (more than 10) of the following errors immediately after starting `iex`:

    maurice@mickey> iex -S mix
    Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

    2018-07-14 09:42:47.061 - pid=<0.184.0> [error] - GenServer #PID<0.184.0> terminating
    ** (FunctionClauseError) no function clause matching in DeltaCrdt.CausalCrdt.handle_info/2
        (delta_crdt) lib/delta_crdt/causal_crdt.ex:154:
          DeltaCrdt.CausalCrdt.handle_info(
               :ship_interval_or_state_to_all,
               %DeltaCrdt.CausalCrdt.State{
                 ack_map: %{},
                 crdt_module: DeltaCrdt.AWLWWMap,
                 crdt_state: %DeltaCrdt.CausalDotMap{
                   causal_context: %DeltaCrdt.CausalContext{
                     dots: #MapSet<[]>,
                     maxima: %{}},
                   keys: #MapSet<[]>,
                   state: %{}},
                 deltas: %{},
                 neighbours: #MapSet<[#PID<0.184.0>]>,
                 node_id: 885081504,
                 notify: {#PID<0.180.0>, :processes_updated},
                 outstanding_acks: %{},
                 sequence_number: 0,
                 ship_debounce: 50,
                 shipped_sequence_number: 0})
        (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
    Last message: :ship_interval_or_state_to_all
    State: %DeltaCrdt.CausalCrdt.State{
      ack_map: %{},
      crdt_module: DeltaCrdt.AWLWWMap,
      crdt_state: %DeltaCrdt.CausalDotMap{
        causal_context: %DeltaCrdt.CausalContext{dots: #MapSet<[]>, maxima: %{}},
        keys: #MapSet<[]>,
        state: %{}},
      deltas: %{},
      neighbours: #MapSet<[#PID<0.184.0>]>,
      node_id: 885081504,
      notify: {#PID<0.180.0>, :processes_updated},
      outstanding_acks: %{},
      sequence_number: 0,
      ship_debounce: 50,
      shipped_sequence_number: 0}

I can send the full extract if needed. I believe this is related with
the change in the CRDT API.

Just to be sure, I did

* download  `fix_issues_cluster` branch and then
  `cd horde && mix do deps.get, compile`
* modified the dependency on the new horde in `XYZ` project
* cleaned up and recompile `XYZ`: `mix do clean --deps, deps.get, compile`

Again, I can send the full trace if needed.

Cheers,

Maurycy

**Comment by mszmurlo** [comment]
Just to make sure I wasn't missing something, I re-cleaned everything and re-tried with the stable (master) version. I'm getting a different error but also in CRDT 

    2018-07-15 09:41:19.557 - pid=<0.252.0> [error] - GenServer #PID<0.252.0> terminating
    ** (FunctionClauseError) no function clause matching in Keyword.get/3
        (elixir) lib/keyword.ex:179: Keyword.get({#PID<0.251.0>, :members_updated}, :notify, nil)
        (delta_crdt) lib/delta_crdt/causal_crdt.ex:48: DeltaCrdt.CausalCrdt.start_link/3
        (horde) lib/horde/supervisor.ex:119: Horde.Supervisor.init/1
        (stdlib) gen_server.erl:365: :gen_server.init_it/2
        (stdlib) gen_server.erl:333: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
        Last message: {:EXIT, #PID<0.251.0>,
          {:function_clause,
           [{Keyword, :get,
             [{#PID<0.251.0>, :members_updated}, :notify, nil], [file: 'lib/keyword.ex', line: 179]},
               {DeltaCrdt.CausalCrdt, :start_link, 3, [file: 'lib/delta_crdt/causal_crdt.ex', line: 48]},
               {Horde.Supervisor, :init, 1, [file: 'lib/horde/supervisor.ex', line: 119]},
               {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 365]},
               {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 333]},
               {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
            State: {:state,
                    {#PID<0.252.0>, Supervisor.Default},
                      :one_for_one, [], :undefined, 3, 5, [], 0, Supervisor.Default,
                      {:ok, {%{intensity: 3, period: 5, strategy: :one_for_one}, []}}}
                    
    2018-07-15 09:41:19.558 - pid=<0.33.0> [info] -
      Application xyz exited:
      XYZ.Application.start(:normal, []) returned an error: shutdown: failed to start child: Horde.Supervisor
        ** (EXIT) an exception was raised:
            ** (FunctionClauseError) no function clause matching in Keyword.get/3
                (elixir) lib/keyword.ex:179: Keyword.get({#PID<0.251.0>, :members_updated}, :notify, nil)
                (delta_crdt) lib/delta_crdt/causal_crdt.ex:48: DeltaCrdt.CausalCrdt.start_link/3
                (horde) lib/horde/supervisor.ex:119: Horde.Supervisor.init/1
                (stdlib) gen_server.erl:365: :gen_server.init_it/2
                (stdlib) gen_server.erl:333: :gen_server.init_it/6
                (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3** (Mix) Could not start application xyz:
                    XYZ.Application.start(:normal, [])
                    returned an error: shutdown: failed to start child: Horde.Supervisor
        ** (EXIT) an exception was raised:
            ** (FunctionClauseError) no function clause matching in Keyword.get/3
                (elixir) lib/keyword.ex:179: Keyword.get({#PID<0.251.0>, :members_updated}, :notify, nil)
                (delta_crdt) lib/delta_crdt/causal_crdt.ex:48: DeltaCrdt.CausalCrdt.start_link/3
                (horde) lib/horde/supervisor.ex:119: Horde.Supervisor.init/1
                (stdlib) gen_server.erl:365: :gen_server.init_it/2
                (stdlib) gen_server.erl:333: :gen_server.init_it/6
                (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

Maurycy

**Comment by derekkraan** [comment]
Hi @mszmurlo 

I think this was due to a version mismatch between horde and delta_crdt. I've updated this branch now (and delta_crdt), tested it on my own app (works), could you take a quick look?

Thanks again for taking the time to test.

Derek

**Comment by derekkraan** [comment]
Hi,

I've made some further performance improvements (mostly on the delta_crdt side) and merged with master (but haven't released anything ... I'd like to test this a little bit more before releasing a new version).

Derek

**Comment by mszmurlo** [comment]
Hi,

I've made some tests and I found an issue in propagation of re-connection information. We will be working with three nodes `nd1`, nd2 `and` `nd3` on supervisors only.

First start `nd1` and check members:

    $ ERL_AFLAGS="-name nd1@127.0.0.1 -setcookie abcd" iex -S mix
    ...
    iex(nd1@127.0.0.1)5> Horde.Cluster.members(XYZ.DSup)
    {:ok,
     %{
       <<108, 208, 136, 124, 54, 193, 228, 74, 68, 159, 174, 162, 113, 142, 155, 18,
         222>> => {:alive, #PID<0.202.0>, XYZ.DSup}
     }}

Do the same on `nd2`

    $ ERL_AFLAGS="-name nd2@127.0.0.1 -setcookie abcd" iex -S mix
    ...
    iex(nd2@127.0.0.1)1> Horde.Cluster.members(XYZ.DSup)
    {:ok,
     %{
       <<162, 138, 176, 25, 144, 45, 224, 235, 239, 219, 153, 185, 145, 178, 145,
         63, 21>> => {:alive, #PID<0.243.0>, XYZ.DSup}
     }}

Now join the supervisors on `nd1` and check the members on `nd1`:

    iex(nd1@127.0.0.1)7> Horde.Cluster.members(XYZ.DSup)
    {:ok,
     %{
       <<108, 208, 136, 124, 54, 193, 228, 74, 68, 159, 174, 162, 113, 142, 155, 18,
         222>> => {:alive, #PID<0.202.0>, XYZ.DSup},
       <<162, 138, 176, 25, 144, 45, 224, 235, 239, 219, 153, 185, 145, 178, 145,
         63, 21>> => {:alive, #PID<16094.243.0>, XYZ.DSup}
     }}

and on `nd2`

    {:ok,
     %{
       <<108, 208, 136, 124, 54, 193, 228, 74, 68, 159, 174, 162, 113, 142, 155, 18,
         222>> => {:alive, #PID<16140.202.0>, XYZ.DSup},
       <<162, 138, 176, 25, 144, 45, 224, 235, 239, 219, 153, 185, 145, 178, 145,
         63, 21>> => {:alive, #PID<0.243.0>, XYZ.DSup}
     }}

So far so good. The global horde is seen on both nodes. Now lets
shutdown `nd1`, restart and restart it **without re-joining the horde**:

    ex(nd2@127.0.0.1)3> :init.stop
    :ok
    iex(nd2@127.0.0.1)4> 
    $ ERL_AFLAGS="-name nd2@127.0.0.1 -setcookie abcd" iex -S mix
    ...
    iex(nd2@127.0.0.1)1> 

Just after `:init.stop` function `handle_topology_changes/1` gets called on `nd1`. This seems OK. `nd2` gets completely down and 10 seconds after it got restarted, I get the following log on `nd2` (re-formated for readability):

    2018-07-22 08:48:09.528 - pid=<0.231.0> 
      module=Horde.SupervisorImpl 
      function=handle_topology_changes/1 [debug] - found 0 out of 0 processes belonging to 
        <<162, 138, 176, 25, 144, 45, 224, 235, 239, 219, 153, 185, 145, 178, 145, 63, 21>>

In other words, `nd2` gets a sync message about its **old incarnation**. I believe the normal behaviour should be not to receive anything until hordes are joined or at least that `nd2` receives all the information held by `nd1`: about `nd2` old incarnation **and** about `nd1` itself. But what happens  seems kind of strange. Listing members on `nd2`, actually shows no info about `nd1`:

    iex(nd2@127.0.0.1)2> Horde.Cluster.members(XYZ.DSup)
    {:ok,
     %{
       <<1, 139, 131, 106, 198, 252, 185, 176, 191, 187, 221, 176, 80, 107, 247,
         196, 84>> => {:alive, #PID<0.231.0>, XYZ.DSup},
       <<162, 138, 176, 25, 144, 45, 224, 235, 239, 219, 153, 185, 145, 178, 145,
         63, 21>> => {:dead, nil, nil}
     }}

Now let's join the horde from `nd2` and check for membership:

    iex(nd2@127.0.0.1)3> Horde.Cluster.join_hordes(XYZ.DSup, {XYZ.DSup, :"nd1@127.0.0.1"})
    true
    iex(nd2@127.0.0.1)5> Horde.Cluster.members(XYZ.DSup)
    {:ok,
     %{
       <<1, 139, 131, 106, 198, 252, 185, 176, 191, 187, 221, 176, 80, 107, 247,
         196, 84>> => {:alive, #PID<0.231.0>, XYZ.DSup},
       <<162, 138, 176, 25, 144, 45, 224, 235, 239, 219, 153, 185, 145, 178, 145,
         63, 21>> => {:dead, nil, nil}
     }}
 
In other words, it looks like it didn't work. Checking for members on `nd1` doesn't give any further information. You would I get the same result if you try to join on `nd1`.

Actually, it worked but the joining event had been stuck somewhere... For the time being we didn't touch to **`nd3`**. So let's start it and join the horde:

    $ ERL_AFLAGS="-name nd3@127.0.0.1 -setcookie abcd" iex -S mix
    ...
    iex(nd3@127.0.0.1)1> Horde.Cluster.join_hordes(XYZ.DSup, {XYZ.DSup, :"nd1@127.0.0.1"})
    true
    2018-07-22 09:33:39.853 - pid=<0.221.0> module=Horde.SupervisorImpl function=handle_topology_changes/1 
      [debug] - found 0 out of 0 processes belonging to 
        <<162, 138, 176, 25, 144, 45, 224, 235, 239, 219, 153, 185, 145, 178, 145, 63, 21>>
    2018-07-22 09:33:39.874 - pid=<0.221.0> module=Horde.SupervisorImpl function=handle_topology_changes/1 
      [debug] - found 0 out of 0 processes belonging to 
      <<162, 138, 176, 25, 144, 45, 224, 235, 239, 219, 153, 185, 145, 178, 145, 63, 21>>

Joining the horde generated topology change messages on **all three nodes**. Listing members on `nd3` gives:

    iex(nd3@127.0.0.1)4> Horde.Cluster.members(XYZ.DSup)
    {:ok,
     %{
       <<1, 139, 131, 106, 198, 252, 185, 176, 191, 187, 221, 176, 80, 107, 247,
         196, 84>> => {:alive, #PID<16135.231.0>, XYZ.DSup},
       <<108, 208, 136, 124, 54, 193, 228, 74, 68, 159, 174, 162, 113, 142, 155, 18,
         222>> => {:alive, #PID<16086.202.0>, XYZ.DSup},
       <<161, 136, 226, 163, 176, 58, 68, 163, 6, 70, 211, 235, 175, 143, 80, 123,
         221>> => {:alive, #PID<0.221.0>, XYZ.DSup},
       <<162, 138, 176, 25, 144, 45, 224, 235, 239, 219, 153, 185, 145, 178, 145,
         63, 21>> => {:dead, nil, nil}
     }}

I get the same kind of results on `nd1` and `nd2`.

I wonder two things:

* Why do you have to keep track of the dead nodes ?
* node ids are random binaries. Isn't it possible to have them in some more readable (and compact) format like strings ?

NB: All this also happens if you kill `nd2` with `Crtl-C Ctrl-C` rather than shutting it down gently.

Just one additional remark: the compiler complains when compiling `xxhash.ex`:

```
warning: variable "description" does not exist and is being expanded to "description()", please use parentheses to remove the ambiguity or change the variable name
  /home/maurice/dev/elixir/xyz/deps/xxhash/mix.exs:9

warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  /home/maurice/dev/elixir/xyz/deps/xxhash/mix.exs:10

warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  /home/maurice/dev/elixir/xyz/deps/xxhash/mix.exs:11
```

I have no time to test in details any further, but I'll send you some reports when I get less busy.

Cheers

**Comment by derekkraan** [comment]
Hi, thanks again for taking the time to test!

I'll start at the bottom, xxhash is a dependency but the developer already merged a PR of mine to fix xxhash in elixir 1.7 so I'll send another PR to fix the compile warnings, should be fairly trivial.

Node IDs are random binaries because I wanted something that I could quickly generate and which would be fast for comparisons but perhaps I'm overstating the benefits. I'll take a look at possibly making them a little easier to read.

I'll check the code to see if we make a distinction between dead nodes and unknown nodes, maybe we can just delete information about a node when it's dead instead of marking it as dead and not removing it from the tracking.

The scenario you detailed does look strange. I'll try to reproduce it tomorrow.

Derek

**Comment by derekkraan** [comment]
I've done a little bit of work on these issues:
- xxhash should not emit any compiler warnings anymore
- I've formatted node ids differently, should be much easier to read now. eg: `iKS+7x3fuU4BRzM9wP+IQQ==`. Same amount of randomness (128 bits) but much easier to read.

I'm now taking a look at removing `:dead` members from the list altogether. Should be doable.

**Comment by derekkraan** [comment]
Hi @mszmurlo,

I've made some more changes to fix these issues. I was able to reproduce the issue mentioned above, and fix it. I've merged all branches back into `master` so if you could pull and give it another go, that'd be a big help!

Cheers
Derek

**Comment by mszmurlo** [comment]
Hi Derek,

I really tried to make your code crash or get into an inconsistent state, but... I failed. And now, listing members is definitely nicer. Good job!

I'm closing this case.

Cheers
Maurycy
