### ISSUE TITLE
Getting started documentation may not be valid anymore?

### ISSUE THREAD

**Issue by pdgonzalez872** [derekkraan/horde#111]
Env details:

```
# OS -> OSX
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Interactive Elixir (1.7.2) - press Ctrl+C to exit (type h() ENTER for help)
```

Issue:
I wanted to add a `GenServer` to the `Horde.Supervisor` supervision tree but was not able to.

Expected behavior:
Can add a child to the supervision tree correctly. Would display in the observer.

Sample app that displays the behavior. You can check the branch out and run `mix test`:
https://github.com/pdgonzalez872/horde/tree/add-horde-only-example/examples/horde_example

I added a silly assertion to fail first before writing a passing test, but I got a different error. I tried in `iex` and got the same behavior. The test will fail with this error:
```
horde_example [add-horde-only-example] :> mix test
Compiling 1 file (.ex)

15:10:32.721 [info]  Starting Horde.SupervisorImpl with name HordeExample.DistributedSupervisor


  1) test use this as an example should work (NetsplitTest)
     test/acceptance_test.exs:5
     ** (MatchError) no match of right hand side value: {:error, {:undef, [{GenServer, :start_link, [], []}, {Horde.DynamicSupervisor, :start_child, 3, [file: 'lib/horde/horde_dynamic_supervisor.ex', line: 765]}, {Horde.DynamicSupervisor, :handle_start_child, 2, [file: 'lib/horde/horde_dynamic_supervisor.ex', line: 751]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 690]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
     code: :ha = HordeExample.add_child_to_supervisor()
     stacktrace:
       test/acceptance_test.exs:6: (test)



Finished in 0.08 seconds
1 test, 1 failure
```

Potential solutions:
- Are the docs here still applicable? https://github.com/derekkraan/horde#usage  This is the line I question: `Horde.Supervisor.start_child(MyApp.DistributedSupervisor, %{id: :gen_server, start: {GenServer, :start_link, []}})`. Maybe there was a change and the docs have not been updated yet.
- I missed a step somewhere.

**Comment by pdgonzalez872** [comment]
Very likely a doc issue.

The following works:
```
    agent_def = %{
      id: "agent_1",
      start:
        {Agent, :start_link,
         [
           fn ->
             %{}
           end
         ]},
      type: :worker,
      shutdown: 10
    }

    Horde.Supervisor.start_child(HordeExample.DistributedSupervisor, agent_def)
```

**Comment by derekkraan** [comment]
Hi,

Your analysis is correct. I will accept a PR to change this to something people can actually use.

Derek

**Comment by pdgonzalez872** [comment]
Alright! Will have it later today! Thank you!
