### ISSUE TITLE
Rename Horde.Supervisor to Horde.DynamicSupervisor

### ISSUE THREAD

**Issue by derekkraan** [derekkraan/horde#131]
Now that we are really API-compatible with `Elixir.DynamicSupervisor`, to avoid confusion in the future we should rename `Horde.Supervisor` to `Horde.DynamicSupervisor`.

**Comment by treble37** [comment]
Just starting to go through horde for the first time and was starting to rename...

So I see `lib/horde/horde_dynamic_supervisor.ex` which already contains `Horde.DynamicSupervisor`...so did you want to rename `Horde.Supervisor` to something else or am I misunderstanding this issue?

**Comment by derekkraan** [comment]
`Horde.DynamicSupervisor` is currently a private module in Horde, you should not use it directly. I would like to rename what is now called `Horde.Supervisor` to `Horde.DynamicSupervisor`, and the current module named that will have to be called something else.

So this is an issue describing what will happen, it is not already like that.

**Comment by Shikanime** [comment]
@derekkraan As i understand so far, since `Horde.DynamicSupervisor` is a supervisor which maintains local processes we could rename it as `WorkersSupervisor` which may be more meaningful of his responsibility.

**Comment by derekkraan** [comment]
@Shikanime it is really just a distributed version of `Elixir.DynamicSupervisor`.

**Comment by Shikanime** [comment]
@derekkraan So can we use its API directly instead of using a forked elixir module, or what is the reason that the Horde is using this module? 🤔

**Comment by derekkraan** [comment]
Right now there is a (private) module in Horde called `Horde.DynamicSupervisor`, this module is a modified version of `Elixir.DynamicSupervisor`. I would like to rename this to something else, so that we can rename the module currently called `Horde.Supervisor` to `Horde.DynamicSupervisor`.

`Horde.DynamicSupervisor` -> `Horde.SomethingElse`
`Horde.Supervisor` -> `Horde.DynamicSupervisor`

The reason being that `Horde.Supervisor` mirrors the API of `Elixir.DynamicSupervisor`, not `Elixir.Supervisor`.

Is this making sense now? I realize that it's a bit confusing since there is already a module called `Horde.DynamicSupervisor.`

**Comment by derekkraan** [comment]
Done in d47a068
