### ISSUE TITLE
Lookup return value when not found is not compatible with Elixr.Registry

### ISSUE THREAD

**Issue by philipbrown** [derekkraan/horde#144]
Hey @derekkraan, thank you for creating Horde. I'm just testing it out on a project and it's working great so far!

One thing I've noticed is `Horde.Registry.lookup/2` returns `:undefined` when there isn't a match, whereas `Elixir.Registry.lookup/2` returns an empty list.

I can send a PR to fix it if you like? 😄

**Comment by derekkraan** [comment]
Yes please!
