### ISSUE TITLE
Redefining supervision entrypoint API

### ISSUE THREAD

**Issue by Shikanime** [derekkraan/horde#149]
**Is your feature request related to a problem? Please describe.**

Today the Horde API seem a little off compared to the DynamicSupervisor which is the implementation reference:

```elixir
defmodule MyApp.DynamicSupervisor do

  use DynamicSupervisor

  def start_link(init_arg) do
    DynamicSupervisor.start_link(__MODULE__, init_arg, name: __MODULE__)
  end

  @impl true
  def init(_init_arg) do
    DynamicSupervisor.init(strategy: :one_for_one)
  end
end
```

**Describe the solution you'd like**

A more similar start API like:

```elixir
defmodule MyApp.HordeSupervisor do
  use Horde.Supervisor

  def start_link(init_arg, options \\ []) do
    Horde.Supervisor.start_link(__MODULE__, init_arg, options)
  end

  def init(_init_arg) do
    Horde.Supervisor.init(strategy: :one_for_one, members: members())
  end

  def members() do
    []
  end
end
```

**Additional context**

Inspiration reference: https://github.com/elixir-lang/elixir/blob/79388035f5391f0a283a48fba792ae3b4f4b5f21/lib/elixir/lib/dynamic_supervisor.ex#L511

**Comment by derekkraan** [comment]
Can you show me how you would do it with Horde today, so that I can see the difference you are proposing?

**Comment by Shikanime** [comment]
As a user I want to define options as we do with `Supervisor / DynamicSupervisor` such as strategy, distribution strategy... in the `init` and start options in the `start_link`. But the API is a bit confusing compared to the Elixir way which don't define the `start_link` by default letting the user implement it himself.

Actual implementation of an Horde Supervisor:

```elixir
defmodule MySupervisor do
  use Horde.Supervisor

  def init(options) do
    {:ok, Keyword.put(options, :strategy, :one_for_one)}
  end
end
```

the start will fail because we did not provide the strategy.

For example today, i want to define the fact that the `Channels` module will use the `one_for_one` strategy in the module level so i do:

```elixir
defmodule Elchea.Channels do
  use Supervisor

  def start_link(options \\ []) do
    name = Keyword.fetch!(options, :name)
    Supervisor.start_link(__MODULE__, options, name: name)
  end

  @impl true
  def init(opts) do
    root_name = Keyword.fetch!(opts, :name)

    children = [
      # ...
      {Horde.Supervisor, [name: resolve(root_name), strategy: :one_for_one]}
      # ...
    ]

    Supervisor.init(children, strategy: :one_for_all)
  end

  def resolve(name) do
    Module.concat(name, "ClusterSupervisor")
  end
end
```

To hide the supervisor's options at the top level of the application, respecting the responsibility of each module:

```elixir
defmodule Constellation.Planet.App do
  @moduledoc false
  use Application

  def start(_type, _args) do
    children = [
      # ...
      Constellation.Planet.Channels
      # ...
    ]

    opts = [strategy: :one_for_one, name: Constellation.Planet.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
```

**Comment by derekkraan** [comment]
In general I am in favour of better compatability with `DynamicSupervisor`.

Doing this change will require bumping the version to 0.7, but I'm ok with that. While we're breaking the API, we should also do #131.

Will you work out a PR for this change? Please also consider whether the same change should be made for `Horde.Registry`.

**Comment by Shikanime** [comment]
Sure, I'm currently working on it on my free time 😇
