### ISSUE TITLE
Horde.Registry using macro no longer provides `start_link/1`

### ISSUE THREAD

**Issue by jeffgrunewald** [derekkraan/horde#165]
In the switch from Horde 0.6.1 to 0.7.0 it appears the default implementation of the `start_link/1` function that was included by default in the using macro has disappeared.

The documentation on Hex for version 0.7.0 indicates this is still intended to be provided as part of the using macro. Is that correct or is the intention to deprecate this behavior in favor of the user always implementing their own `start_link/1`?

Thanks very much!

**Comment by derekkraan** [comment]
Hi @jeffgrunewald, `start_link/1` was removed from the macro to bring it in line with `Elixir.DynamicSupervisor`, which also does not provide `start_link/1`.

Could you send a PR to bring the documentation in line?

Thanks!

**Comment by jeffgrunewald** [comment]
Absolutely. Thanks for clarifying.
