### ISSUE TITLE
Erlang 20 and Elixir 1.6.1 and example not running correctly

### ISSUE THREAD

**Issue by shifters67** [derekkraan/horde#17]
Hi,

I have tried running your example on ubuntu 18.04.

The two nodes start fine but **both** display the hello message with their own node details rather than just one of them  (I cut and pasted the start code from the example readme into each terminal)

Killing one of the nodes does not cause the other node to pick up the lost process.

Running Node.list shows that both are connected to each other.

Am i doing something wrong?

regards

Tom

**Comment by derekkraan** [comment]
And can you show me the commands you are running to start the example?

**Comment by derekkraan** [comment]
I have tested with Erlang 20.1 and Elixir 1.6.1 on my machine (Arch) and the examples work as expected. If you can give me some more information then I can understand better why the example isn't working for you.

I'm closing this in the meantime, feel free to re-open when you add more details.
