### ISSUE TITLE
Use PG2 as default cluster formation

### ISSUE THREAD

**Issue by Shikanime** [derekkraan/horde#171]
It would be more convenient to create a cluster of `DynamicSupervisor` / `Registry` using PG2 by default such as `Phoenix.Pubsub`.

**Comment by derekkraan** [comment]
Can you elaborate?

**Comment by Shikanime** [comment]
Actually every Horde components are discovered statically via Erlang node name:

```elixir
{HelloWorld.HelloDynamicSupervisor, :"count1@127.0.0.1"}
```

In the case of a dynamic cluster such as under a container orchestrator like Kubernetes, we have to monitor the node to join or leave and ensure proper synchronization of the Horde cluster on the user space can be sometime less convenient.

Instead the component should join the pg2 `{:horde, name}` group at startup where name can be  `HelloWorld.HelloDynamicSupervisor`.

What do you think ?

**Comment by derekkraan** [comment]
I think I would rather leave this up to the person who is using Horde. If you would like to submit a PR documenting how to get Horde working with pg2, then I would accept that.
