### ISSUE TITLE
Supervised processes on node removal

### ISSUE THREAD

**Issue by bernardd** [derekkraan/horde#172]
Hi - first, thanks for Horde - it's pretty awesome :)

I feel like I must either be missing something or have misunderstood the expected behaviour, however. In particular: When the node that a supervised process is running on is either brought down (kill `beam.smp`, pull the power plug, whatever) or explicitly removed from the cluster (via a `Horde.Cluster.set_members/2` call), would it be expected that that process is restarted on one of the remaining cluster nodes? The docs don't explicitly say one way or the other (at least as far as I could see). My hope/naive expectation would be that it would but in all the tests I've run it seems like the process just disappears from the supervised children list (returned by `Horde.DynamicSupervisor.which_children/1`), never to be seen again.

The only explicit mention I've been able to find anywhere was in #86 which mentions in passing that

> when a node leaves the cluster its processes will be evenly distributed across the remaining nodes

but of course that's by no means an authoritative source :)

Looking at the code, my impression is that each node supervisor maintains its own child list once it's started a child, and therefore killing the node loses the contents of that list. But I could very easily have missed something.

If the answer is "no, it won't be restarted", is that a feature you'd consider adding if I were able to code it up?

**Comment by derekkraan** [comment]
Hi,

Yes, it will be restarted. There is a minor caveat to that, if you have started your process with `restart: :temporary`, then it will not be restarted.

I believe this is also mentioned in the readme: https://github.com/derekkraan/horde/#fault-tolerance

But if you feel that there is something missing from the documentation, then I would be more than happy to accept a PR improving that.

Does this answer your question? Horde replicates all the information necessary to start any child process across all nodes, and when a node goes down, it should normally be restarted on another node. If this isn't happening, then I'm curious as to why and perhaps we should investigate further.

Derek

**Comment by bernardd** [comment]
Definitely answers my question about what's meant to happen, yes, thanks :)
Doesn't answer why it doesn't seem to be happening in my tests, but at least I know what should be happening so I can either a) figure out what I've done wrong or b) at least construct an example to show you so you can tell me what I'm doing wrong :)

**Comment by derekkraan** [comment]
Sounds good, let me know what you find.

**Comment by bernardd** [comment]
> I believe this is also mentioned in the readme: https://github.com/derekkraan/horde/#fault-tolerance

Dangit, quite right. Sorry I missed that.

Okay, so I've got a relatively minimal case that demonstrates the issue I'm hitting.

First, a trivial GenServer:

```elixir
defmodule TestServer do
  use GenServer, restart: :permanent

  def start_link(_) do
    GenServer.start_link(__MODULE__, [], name: __MODULE__)
  end

  def init(_) do
    {:ok, nil}
  end
end

```

Then a dumb distribution strategy that ensures we're going to start things on a remote node (so that we can take it down without killing our test) - this isn't necessary to see the problem but it makes it easier to replicate:

```elixir
defmodule DistStrat do
  @behaviour Horde.DistributionStrategy

  def choose_node(_id, members), do: {:ok, List.last(members)}
  def has_quorum?(_members), do: true
end
```

And finally an ExUnit test:
```elixir
defmodule HordeTest do
  use ExUnit.Case

  test "simple nodedown test" do
    nodes = [node() | LocalCluster.start_nodes("test-cluster", 2)]
    :rpc.multicall(nodes, Application, :ensure_all_started, [:horde])

    sup_members = for n <- nodes, do: {Test.DynamicSupervisor, n}

    for n <- nodes do
      :rpc.block_call(n, Horde.DynamicSupervisor, :start_link, [
        [
          id: Test.DynamicSupervisor,
          name: Test.DynamicSupervisor,
          strategy: :one_for_one,
          distribution_strategy: DistStrat,
          members: sup_members
        ]
      ])
    end

    Process.sleep(1000)

    {:ok, pid} =
      Horde.DynamicSupervisor.start_child(Test.DynamicSupervisor, TestServer)

    IO.inspect "Before Node shutdown: #{inspect Horde.DynamicSupervisor.which_children(Test.DynamicSupervisor)}"

    LocalCluster.stop_nodes([:erlang.node(pid)])

    Process.sleep(2000)

    IO.inspect "After Node shutdown: #{inspect Horde.DynamicSupervisor.which_children(Test.DynamicSupervisor)}"
  end
end
```

Running this, here's the output I get:

```
10:54:04.058 [info]  Starting Horde.DynamicSupervisorImpl with name Test.DynamicSupervisor

10:54:04.208 [info]  Starting Horde.DynamicSupervisorImpl with name Test.DynamicSupervisor

10:54:04.208 [info]  Starting Horde.DynamicSupervisorImpl with name Test.DynamicSupervisor

10:54:04.386 [info]  Starting Horde.DynamicSupervisorImpl with name Test.DynamicSupervisor

10:54:04.386 [info]  Starting Horde.DynamicSupervisorImpl with name Test.DynamicSupervisor
"Before Node shutdown: [{:undefined, #PID<18074.218.0>, :worker, [TestServer]}]"
"After Node shutdown: []"
.

Finished in 5.7 seconds
1 test, 0 failures

Randomized with seed 707355
```

As you can see the output of `Horde.DynamicSupervisor.which_children/1` shows an empty list after removing the node running the supervised process. (And when I have that process register a name using `Horde.Registry` sure enough that name no longer resolves - I left that out for the sake of brevity).

As a side note I'm also not 100% sure why I get the "Starting" message 5 times when I'm only starting 3 instances of the supervisor (as far as I know).

Thanks heaps for any help :)

**Comment by derekkraan** [comment]
Thanks for checking this out for me. I'm going to try to look into this more deeply today.

**Comment by bernardd** [comment]
Hi @derekkraan I was wondering if you'd had a chance to look at this and if there was anything I could do to help figure out what's happening. My main difficulty with debugging the first time around was that I couldn't see which part of the code was meant to handle the remote restart. If you can point me in the right direction, I'm more than happy to spend some time on it myself.

**Comment by derekkraan** [comment]
Hi @bernardd, I have made some time free to look at this today. The part of the code that you're looking for is here: https://github.com/derekkraan/horde/blob/master/lib/horde/dynamic_supervisor_impl.ex#L405

This bit of the code has changed recently and I'm not 100% sure I'm happy with it (in terms of code style; in terms of functionality I think it's fine). So it may change again in the short term future.

**Comment by derekkraan** [comment]
With that said, I am suspicious that the test is incorrect and that the problem is that the supervisor is being shut down before it has had time to propagate the existence of its child processes to the other nodes in the cluster.

**Comment by bernardd** [comment]
Hey @derekkraan - I did consider the issue of timing in my tests, and tried sleeps at a number of different spots. Just to be sure, though, here's the pertinent bit of code modified with some extra and longer sleeps:

```elixir
    Horde.Cluster.set_members(Test.DynamicSupervisor, sup_members)

    Process.sleep(10000)

    {:ok, pid} =
      Horde.DynamicSupervisor.start_child(Test.DynamicSupervisor, TestServer)

    Process.sleep(10000)

    IO.inspect "Before Node shutdown: #{inspect Horde.DynamicSupervisor.which_children(Test.DynamicSupervisor)}"

    LocalCluster.stop_nodes([:erlang.node(pid)])

    Process.sleep(10000)

    IO.inspect "After Node shutdown: #{inspect Horde.DynamicSupervisor.which_children(Test.DynamicSupervisor)}"
```
And it still produces the same output as above (albeit more slowly :)).

**Comment by bernardd** [comment]
> The part of the code that you're looking for is here:
Thanks - I'll have a dig into this today.

**Comment by bernardd** [comment]
Oh my goodness. I'm an idiot. My "super simple" distribution strategy was a little too simple for its own good. Its `choose_node/2` consistently chose the dead node because it didn't filter it out first. Fixed that and all is well. Thanks heaps for your help and apologies for the non-bug.
