### ISSUE TITLE
Configurable distribution strategy

### ISSUE THREAD

**Issue by arjan** [derekkraan/horde#192]
I would like to pass some options to the `distribution_strategy` at runtime via the supervision tree, just like you configure a Plug. Would this be a good idea? This would mean that the call signatures of the behaviour would change:

```
choose_node(identifier, members, opts)
has_quorum?(members, opts)
```

and maybe also an init() function:
```
init(opts) :: opts
```

**Comment by derekkraan** [comment]
What kind of options will you pass to the distribution strategy? And would you be able to for example just statically build it into the distribution strategy instead?

**Comment by arjan** [comment]
Yeah you are right, that is how I am doing it now, The configuration can be compile-time in my case, I needed a uniform strategy but with a filter on the node names.

**Comment by arjan** [comment]
For future reference, the following creates a NodePrefix module that can be used to create a distribution strategy that only selects nodes that share a common prefix

```elixir
  defmodule NodePrefix do
    def filter(members, prefix) do
      members
      |> Enum.filter(fn member ->
        %{name: {_, node}} = member

        node
        |> to_string
        |> String.starts_with?(prefix)
      end)
    end

    defmacro __using__(prefix) do
      quote do
        import unquote(__MODULE__)

        def choose_node(identifier, members) do
          members = filter(members, unquote(prefix))
          Horde.UniformDistribution.choose_node(identifier, members)
        end

        def has_quorum?(_members), do: true
      end
    end
```

You create your own fixed strategy (that uses all nodes starting with `web@`) like this:
```
  defmodule MyWebNodesDistribution do
    use NodePrefix, "web@"
  end
end
```
