### ISSUE TITLE
State handoff

### ISSUE THREAD

**Issue by dazuma** [derekkraan/horde#21]
Great work on Horde! I just got finished porting a project over from Swarm, and it seems to be working much more stably under Horde—mostly, I think, because of the graceful shutdown decoupled from node shutdown. I've also found Horde's source much easier to follow than Swarm's, so kudos.

One of the requirements of my app is handoff of state when a process gets restarted on another node using Horde.Supervisor. (Consider, for example, an app running on Kubernetes where containers can be killed due to scaling down or as part of a rolling update, and you want long-running processes to migrate to other live containers along with their state.) This is something that Swarm does, and I imagine it may be a fairly common requirement.

I got this working for my app by creating a _third_ horde type called "Handoff" that basically just wraps another CRDT with a mapping from process name to saved state. (My implementation borrows heavily from the current Horde.Registry module.) Processes that are about to be terminated can save their state to the Handoff CRDT, and when they start up they can check for saved state on the CRDT.

I was wondering if you have particular plans for a feature like this in Horde, and if you have any ideas or feedback on implementation. I could even try cleaning up my implementation as a pull request if you're interested.

**Comment by derekkraan** [comment]
Hi,

First off, thanks :). It's good to see some interest (you are a trailblazer, as far as I am aware, nobody is running Horde in production -- I am close, but still ~2 months away).

I haven't got any particular plans for a feature like this in Horde, but it is something I've been asked about several times. The general approach you've taken (persisting state in a `terminate/2` callback) sounds good to me (and I specifically don't want to build it into `Horde.Supervisor` in a more integrated way like `Swarm` does).

I'd be interested to see your implementation.

Cheers,
Derek

**Comment by dazuma** [comment]
My project really isn't in "production". It's an experiment/demo that I use to show that I can have long-running stateful processes on Kubernetes. (I'm also running Horde from master rather than the 0.1.5 release, if that matters—and indeed, I'm running a [patched version](https://github.com/dazuma/horde/tree/tanx) to deal with #16 which I ran into regularly.)

You can see the implementation in [this project](https://github.com/dazuma/tanx).

The [Handoff](https://github.com/dazuma/tanx/blob/master/apps/tanx/lib/tanx/util/handoff.ex) module again borrows heavily from the current Horde.Registry. (Indeed I might have used Horde.Registry itself if it worked with arbitrary terms like the standard [Registry](https://hexdocs.pm/elixir/Registry.html) module.) I copied over the same pattern of using a "members" CRDT and a "data" CRDT, and it responds to the same `:join_hordes` message. I do agree with #18 that it might be worth refactoring this to put the CRDT processes under a supervision tree. And as an aside, maybe the join logic and "members" CRDT boilerplate could be abstracted out, to make it easier to write this kind of module with, say, `use Horde`?

The expected usage is:
  * You should call `Handoff.store/3` from the `terminate/2` callback, to store state on the CRDT.
  * On process reinitialization, you should call `Handoff.request/4`. This will return either `{:ok, :data, data}` with the stored state (and remove it from the CRDT), or, if the data has not yet propagated to the local node, will return `{:ok, :requested}`. In the latter case, then when the data arrives (via the CRDT notify message), a message will be sent with the stored state.
  * In case the process decides later that it no longer wants to accept handoff state, it should remove its request by calling `Handoff.unrequest/2`.

A usage example is in [this GenServer](https://github.com/dazuma/tanx/blob/master/apps/tanx/lib/tanx/game/manager.ex):
  * See `do_handoff/1` which is called from `terminate/2` and calls `Handoff.store/3`.
  * See `do_up/2` which is called automatically during initialization and requests state with `Handoff.request/4`. But when the process is first started, it is called a second time with explicit state (see `handle_call({:up, data}, ...)`, and thus calls `Handoff.unrequest/2`.

**Comment by derekkraan** [comment]
@dazuma Right on! I can't think of anything specifically that you should mention. Good luck with your talk! I'll try not to release any risky features this week ;)

**Comment by derekkraan** [comment]
@arjan I was wondering if I could ask you for some feedback on this. You've got state handover going with swarm, and I believe your approach is similar to this (save and load from Redis?). I'd like to get this into Horde, but I'd also like to hear from at least one other person who's actually using state handover.

**Comment by tompave** [comment]
Hi @derekkraan,

Has there been any change on this? I'm currently evaluating Horde vs Swarm for a project, and a builtin way to do state handoff is a nice plus.

I can see that https://github.com/derekkraan/horde/pull/33 has been merged, which makes me think that it's now possible to use `Horde.Registry` to replicate state in the cluster, in a way similar to what @dazuma did with his custom [CRDT-based](https://hex.pm/packages/delta_crdt) handoff processes ([great talk](https://www.youtube.com/watch?v=nLApFANtkHs), also). I'm asking because I can't see any doc changes in PR, and no mention of the new capability elsewhere (is there a plan to add a changelog and versioned git tags?), so I'm not sure if this is going in that specific direction.

If it is, I was wondering about the memory usage implications. I understand that Swarm's handoff will only kick in when a process is terminating, and there seem to be some gotchas about losing state when a node terminates. The solution suggested here (a persistent Handoff process) seems more reliable, but it sounds like it would use much more memory. For example, if I had 30 nodes with 1000 Horde-managed processes on each, I'd have to replicate the state of 30k processes on each node. Is that correct? Or there are more efficient ways to use it?

I also find your mention of @arjan's Redis-backed solution interesting. It reminds me of [Akka Persistence and `PersistentActor`](https://doc.akka.io/docs/akka/2.5/persistence.html), which is close to what I'd like, I think.

**Comment by derekkraan** [comment]
Hi @tompave,

`Horde.Registry` has gotten some improvements that should make it easier to implement state handoff in a reasonable manner. There hasn't been any work done on building a solution for state handoff into Horde, but it's a topic I'm interested in exploring in the future.

I can't give a timeline on when this will happen, as any features that aren't necessary for a particular job are built on my own time or subject to volunteer contributions.

If you are considering a persistent Handoff process, it would probably be best to write to the process in the `terminate` callback and read from it again in the `init` callback. This should restrict high memory usage to times when large amounts of processes are being terminated and moved to another node (eg, during a rolling deploy). If you want to persist every single state change, you should just consider building in persistence (to a database perhaps, or Redis) into your process itself and loading its state in `init`, but that's not really so much about handoff anymore as it is about persistence.

**Comment by derekkraan** [comment]
RE: Changelog, aside from commit logs, there is currently no Changelog. I will definitely add one for post-1.0, and might add one before then.

**Comment by tompave** [comment]
Thanks, for the comments, makes sense.

**Comment by derekkraan** [comment]
I am going to close this issue. I am adding a section in the docs for how to implement state handoff #133, and if anyone would like to write a library that makes this easier, then I will be happy to include a link in the readme / in the docs.
