### ISSUE TITLE
Specify options to the regular Supervisor wrapping DynamicSupervisor processes

### ISSUE THREAD

**Issue by stuartish** [derekkraan/horde#215]
### The Problem

The process supervising the DynamicSupervisorImp itself is not currently getting accurate info about how many times DynamicSupervisorImpl (or another part of the system) has restarted. The cryptic layer of supervision is introduced on line 217 of dynamic_supervisor.ex. Essentially, if a child process reaches max_restarts within max_seconds, this causes the DynamicSupervisorImpl to crash. But this can happen 3 times within 5 seconds before the (regular) supervisor wrapping DynamicSupervisorImpl will actually crash, and thus be visible to its own supervising process, and there is currently no way to change that.

### Would Be Nice

If we could include the horde supervisor within a supervision tree that uses :one_for_rest, where the dynamic supervisor is the first child, to add, for instance, some default children.

### Possible Solution

One solution would be to include `max_restarts: 0` on line 217 when initializing the supervisor. This would collapse the supervision tree and always propagate crashes of DynamicSupervisorImpl, more closely emulating DynamicSupervisor behavior.

There's a less "breaking changes" type of solution tho...my proposal:
```
From 9ec161b6478b17627971cff1bdcf997da09ff6b0 Mon Sep 17 00:00:00 2001
From: Stuart Ballard <stuartrballard@gmail.com>
Date: Mon, 19 Oct 2020 20:17:12 -0500
Subject: [PATCH] to allow setting max_restart to 0

---
 lib/horde/dynamic_supervisor.ex | 10 ++++++++--
 1 file changed, 8 insertions(+), 2 deletions(-)

diff --git a/lib/horde/dynamic_supervisor.ex b/lib/horde/dynamic_supervisor.ex
index 3d79e30..8de84f9 100644
--- a/lib/horde/dynamic_supervisor.ex
+++ b/lib/horde/dynamic_supervisor.ex
@@ -149,6 +149,11 @@ defmodule Horde.DynamicSupervisor do
     delta_crdt_options = Keyword.get(options, :delta_crdt_options, [])
     process_redistribution = Keyword.get(options, :process_redistribution, :passive)

+    supervisor_options =
+      options
+      |> Keyword.get(:supervisor_options, [])
+      |> Keyword.merge(strategy: :one_for_all)
+
     distribution_strategy =
       Keyword.get(
         options,
@@ -165,7 +170,8 @@ defmodule Horde.DynamicSupervisor do
       distribution_strategy: distribution_strategy,
       members: members,
       delta_crdt_options: delta_crdt_options(delta_crdt_options),
-      process_redistribution: process_redistribution
+      process_redistribution: process_redistribution,
+      supervisor_options: supervisor_options
     }

     {:ok, flags}
@@ -214,7 +220,7 @@ defmodule Horde.DynamicSupervisor do
           {Horde.DynamicSupervisorTelemetryPoller, name}
         ]
         |> maybe_add_node_manager(flags.members, name)
-        |> Supervisor.init(strategy: :one_for_all)
+        |> Supervisor.init(flags.supervisor_options)

       :ignore ->
         :ignore
--
2.24.1 (Apple Git-126)
```

Just providing the ability to set the options passed to that supervisor. No effect on anyone's existing systems, but I think this would solve more people's problem's than just mine.

Thoughts?

**Comment by derekkraan** [comment]
I don't think we need to make this configurable to end users, and I also doubt it would break anyone's system. So let's go with `One solution would be to include max_restarts: 0 on line 217 when initializing the supervisor.` Can you send a PR?
