### ISSUE TITLE
Common race condition combining Horde.Supervisor and Horde.Registry with :via tuples

### ISSUE THREAD

**Issue by dazuma** [derekkraan/horde#22]
I'm starting processes under a Horde.Supervisor, and using `:via` tuples to register them with a Horde.Registry. I'm encountering a frequent race condition that appears to look like this:

* I have two nodes, A and B.
* On node A, I call `Horde.Supervisor.start_child` to start a process that also registers itself using `name: {:via, Horde.Registry, ...}`
* Horde decides the process should be started on node B, and proxies the request over there.
* Node B starts the process and registers it under the Horde.Registry on node B.
* The reply goes back to my code on node A.
* Node A then wants to call the new process immediately, and passes the same `:via` tuple to `GenServer.send`. Unfortunately, the new registry entry probably has not yet propagated back to node A. So the call crashes. Indeed, without polling the registry, I can't find a good way to determine when the call is safe to make.
* (I know you can just use the returned pid directly, but that becomes more complicated when, as is my case, the child being started is itself a supervisor and I want to call one of its children.)

I've been poking through the horde source and can't see an obvious way to solve this one, without forcing horde to start the process on the local node. (Is there a way to do that?) Currently, I'm using the returned supervisor pid, iterating its children and looking for the recipient pid directly for those "immediate" calls. But it seems a clumsy way to proceed. Wondering if you have any solutions/suggestions. At the very least, it might be worth documenting this since it's likely to be a common problem.

**Comment by derekkraan** [comment]
I acknowledge this problem (and we have indeed "solved" it here by returning a PID). It would be nice to have a better solution.

Forcing Horde to start a process on a particular node would break the consistency guarantee that we have when cluster membership is constant, so we should avoid that if it's at all possible.

Maybe we can solve this by guessing which node the process will have been started on and proxying the request through? (similar to https://github.com/derekkraan/horde/blob/master/lib/horde/supervisor_impl.ex#L218).

What do you think?

**Comment by derekkraan** [comment]
I am a little bit stumped on this one. The CRDT that backs Horde.Registry is by its nature eventually consistent.

It's also not possible to force Horde to start a process on a particular machine, since that breaks the consistency guarantee of the hash ring.

We've solved a similar problem in Horde.Supervisor by proxying calls through to where the requested process would have been started. We can't make a similar prediction in Horde.Registry because we don't have information about the internals of Supervisor, so a possible alternative would be simply proxying through to all neighbours. This has obvious performance implications, since any "miss" would result in messages being sent to all neighbours.

I'm going to park this issue for now and wait for some additional feedback from other people who are running into the same problem. To anyone who's reading this issue: if you're seeing the same issue, please leave a comment in this thread. Suggestions are especially welcome.

**Comment by quolpr** [comment]
+1, it seems I have the same issue 🤔

**Comment by pkinney** [comment]
Using the example in the above PR (#120), I can cause the race condition to occur pretty regularly by using the `:via` method [here](https://github.com/pkinney/horde/blob/97505e56400fbf751c783c03604f61d9d35d47eb/examples/counter/lib/counter/router.ex#L13-L23).

```
> Counter.Router.Via.value(:foo)
** (exit) exited in: GenServer.call({:via, Horde.Registry, {Counter.Registry, :foo}}, :value, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:979: GenServer.call/3
> Counter.Router.Via.value(:foo)
0
```

As mentioned, using the PID directly avoids this race condition:

```
> Counter.Router.PID.value(:bar)
0
> Counter.Router.PID.value(:foo)
0
```

**Comment by derekkraan** [comment]
I think I am comfortable closing this issue. This race condition is inherent in Horde's eventual consistency model. You can now control how often DeltaCrdt syncs between nodes, so it should in theory be possible to make a good prediction of how long you have to wait before the information is propagated to all nodes.

**Comment by BrendanBall** [comment]
I just recently came across this and decided to fix it with events. I use a registry listener genserver that tracks processes waiting for a particular key to be registered and replies as soon as the registered event comes in. 
This seems to be working pretty well.

**Comment by derekkraan** [comment]
@BrendanBall this sounds like it would make an excellent addition to the documentation.
