### ISSUE TITLE
Old child specs remain in Supervisor CRDT after process handoff

### ISSUE THREAD

**Issue by arjan** [derekkraan/horde#262]
When an [existing child spec is added to the CRDT during process handoff](https://github.com/derekkraan/horde/blob/master/lib/horde/dynamic_supervisor_impl.ex#L425), the old child spec is never removed from the CRDT, creating lingering child specs which results in "zombie" processes spawning when a new supervisor is started.

I managed to reproduce this, the fix is to explicitly remove the old child from the CRDT in the supwervisor. PR to follow.

**Comment by drichardson** [comment]
@arjan do you remember how you managed to reproduce this?
