### ISSUE TITLE
Horde.Supervisors supports transient and temporary processes

### ISSUE THREAD

**Issue by derekkraan** [derekkraan/horde#36]
Currently `Horde.Supervisor` only supports permanent processes. For feature-parity with `DynamicSupervisor`, supporting `transient` and `temporary` processes is needed.

**Comment by derekkraan** [comment]
Hi @QuantamHD,

This is correct. We use DynamicSupervisor for doing the actual supervision, and the challenge with `temporary` and `transient` processes is reflecting this information in the δ-CRDT. In the case of `permanent` processes, the state is leading, but in the case of `temporary` or `transient` processes, this is reversed.

For an overview of the behaviour of `temporary` and `transient`, see https://hexdocs.pm/elixir/Supervisor.Spec.html#module-restart-values-restart

I have shied away from doing "real" supervision in `Horde.Supervisor`, preferring to delegate this to `DynamicSupervisor`. This won't be possible anymore if we support transient and temporary children.

If you have any other questions, don't hesitate to ask!

**Comment by QuantamHD** [comment]
In terms of "leading" state do you mean that the state can be set before process creation and not modified afterward for permanent strategies? While for the temporary and transient cases require CRDT modification at process creation time as well as process exits?

**Comment by QuantamHD** [comment]
I would say that makes sense to me. We could also base the implementation off of https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/dynamic_supervisor.ex given that Horde currently tries to maintain API parity with it.

**Comment by QuantamHD** [comment]
One question I do have is can a temporary process actually be restarted in Horde given the strict definition provided in the docs? It sounds like a node down should kill it.

**Comment by derekkraan** [comment]
> We could also base the implementation off Elixir's DynamicSupervisor
This sounds like a very good option. If our changes are limited, then we will also be able to port any changes / bugfixes etc from the stdlib DynamicSupervisor back to Horde's forked version and keep them mostly in sync.

> One question I do have is can a temporary process actually be restarted in Horde given the strict definition provided in the docs? It sounds like a node down should kill it.
I hadn't thought about this. We are extending Supervisor into places it has not been before, so some interpretation is required. In this case I think _never_ restarting is the correct behaviour as you say. For processes that should always be restarted until they have a normal exit code, we have `:transient`.

**Comment by QuantamHD** [comment]
Keeping the bug fixes of stdlib DynamicSupervisor sounds great! It looks like we would need to insert CRDT modification code [here](https://github.com/elixir-lang/elixir/blob/c5a3943e71d7455dedf511a75010adcf8afa732b/lib/elixir/lib/dynamic_supervisor.ex#L890). Could you explain to me the current  "supervision by proxy" strategy employed by Horde? I see that you select nodes bases a consistent hash scheme, and it looks like you forward child specs to that node based on that. If we employed a custom Supervisor how might that strategy change?

**Comment by derekkraan** [comment]
The current strategy is to let `DynamicSupervisor` do all our supervision for us. So we proxy all calls either down to the `DynamicSupervisor` or to the DeltaCRDT (depending on what information is desired).

There is already a use case that I have had to work around (when the CRDT is not "leading"), and that's during a shutdown. During a shutdown, what we want is to update the CRDT state for each process as they shut down, and not at the end, after all processes have shut down. This is because there could be a big difference in shutdown time per process, and we don't want to have a scenario where a process shuts down and then has to wait for all other processes on the node to shut down before it is started on another node. So this is already a chink in the armour of our "supervision by proxy" approach.

And the way this works in practice is that there is a "graceful shutdown" process that recognizes when a shutdown has been initiated and proxies terminate messages from the `ProcessCanary` processes when there is a shutdown ongoing.

So this "graceful shutdown" behaviour is a candidate for improvement if we fork DynamicSupervisor.

I don't think the hash scheme ("distribution strategy") details will change if we fork DynamicSupervisor. This is purely for choosing which node a process should start on, and doesn't have anything to do with supervision of the process once it has actually started.

**Comment by derekkraan** [comment]
Implemented in #70
