### ISSUE TITLE
Dead nodes are not removed from horde registry

### ISSUE THREAD

**Issue by farhadi** [derekkraan/horde#56]
Hi Derek,
We are planning to switch from Swarm to Horde but after doing some tests I saw that when I restart a node, dead node is not removed from horde registry members list and I receive this error: `Discarding message {delta ...` which I believe is because of trying to send deltas to a dead node.
Restarting nodes causes the registry members list to grow and amount of errors is also increased.
I don't know if it is a bug or I'm doing something wrong.

**Comment by derekkraan** [comment]
Hi Ali,

Could you try with the current Horde master branch and let me know if you're still seeing this behaviour? I have been meaning to roll a new release, as some issues such as this should be fixed.

Derek

**Comment by farhadi** [comment]
I tested with current master branch using included hello_world example.

First I start two nodes and everything is fine:
```
iex(count1@127.0.0.1)1> Horde.Cluster.members(HelloWorld.HelloRegistry) 
{:ok,
 %{
   "MbAqzbUD9KNrbLIxEY+faA==" => %{
     keys_pid: #PID<0.206.0>,
     members_pid: #PID<0.198.0>,
     own_pid: #PID<0.210.0>,
     registry_pid: #PID<0.202.0>
   },
   "cg+xMC3lJCOUYmgcTI27Pw==" => %{
     keys_pid: #PID<20632.204.0>,
     members_pid: #PID<20632.196.0>,
     own_pid: #PID<20632.208.0>,
     registry_pid: #PID<20632.200.0>
   }
 }}
```
```
iex(count2@127.0.0.1)1> Horde.Cluster.members(HelloWorld.HelloRegistry) 
{:ok,
 %{
   "MbAqzbUD9KNrbLIxEY+faA==" => %{
     keys_pid: #PID<17991.206.0>,
     members_pid: #PID<17991.198.0>,
     own_pid: #PID<17991.210.0>,
     registry_pid: #PID<17991.202.0>
   },
   "cg+xMC3lJCOUYmgcTI27Pw==" => %{
     keys_pid: #PID<0.204.0>,
     members_pid: #PID<0.196.0>,
     own_pid: #PID<0.208.0>,
     registry_pid: #PID<0.200.0>
   }
 }}
```
But after restarting one of the nodes, I receive this `Discarding message {delta, ...` error and `members` returns 3 items in both nodes:
```
iex(count1@127.0.0.1)2> Horde.Cluster.members(HelloWorld.HelloRegistry) 
{:ok,
 %{
   "B1wfSzsxs3Py18QSzNmOfQ==" => %{
     keys_pid: #PID<20632.204.0>,
     members_pid: #PID<20632.196.0>,
     own_pid: #PID<20632.208.0>,
     registry_pid: #PID<20632.200.0>
   },
   "MbAqzbUD9KNrbLIxEY+faA==" => %{
     keys_pid: #PID<0.206.0>,
     members_pid: #PID<0.198.0>,
     own_pid: #PID<0.210.0>,
     registry_pid: #PID<0.202.0>
   },
   "cg+xMC3lJCOUYmgcTI27Pw==" => %{
     keys_pid: #PID<20632.204.0>,
     members_pid: #PID<20632.196.0>,
     own_pid: #PID<20632.208.0>,
     registry_pid: #PID<20632.200.0> 
   }
 }}
```
```
iex(count2@127.0.0.1)2> Horde.Cluster.members(HelloWorld.HelloRegistry) 
{:ok,
 %{
   "B1wfSzsxs3Py18QSzNmOfQ==" => %{
     keys_pid: #PID<0.204.0>,
     members_pid: #PID<0.196.0>,
     own_pid: #PID<0.208.0>,
     registry_pid: #PID<0.200.0>
   },
   "MbAqzbUD9KNrbLIxEY+faA==" => %{
     keys_pid: #PID<17991.206.0>,
     members_pid: #PID<17991.198.0>,
     own_pid: #PID<17991.210.0>,
     registry_pid: #PID<17991.202.0>
   },
   "cg+xMC3lJCOUYmgcTI27Pw==" => %{
     keys_pid: #PID<0.204.0>,
     members_pid: #PID<0.196.0>,
     own_pid: #PID<0.208.0>,
     registry_pid: #PID<0.200.0>
   }
 }}
```

And more restarts leads to more errors and more items returned by `Horde.Cluster.members`

**Comment by derekkraan** [comment]
Hi Ali,

I've done some testing, PR #57 should fix the issue. Can you please test and report back whether it works as expected?

Cheers
Derek

**Comment by farhadi** [comment]
Thanks for the quick update.
I tested with your PR and found a few issue which I tried to fix here: https://github.com/farhadi/horde/commit/4ddf974bc780d55ee83f282903f220316e9a5af9
can you take a look at my changes.

**Comment by derekkraan** [comment]
Can you describe the issue that you found?

**Comment by farhadi** [comment]
- `mark_dead` was defined between two clauses of handle_info
- `state.members` was not defined (I used `DeltaCrdt.read(state.members_pid, 30_000) )` to retrieve members
- I think `mark_alive(state)` was not needed here

**Comment by derekkraan** [comment]
Ah ok. I agree with all the changes except this one:

> I think mark_alive(state) was not needed here so I removed it

This is needed because we also need to cover the scenario that there is a netsplit, and the node is not actually dead.

Can you restore `mark_alive` and open a PR on the branch `remove_dead_members`?

**Comment by farhadi** [comment]
Here it is: https://github.com/derekkraan/horde/pull/58

**Comment by derekkraan** [comment]
Thanks for your help @farhadi. I'll release an rc so that people can test a bit before I publish the final release.

**Comment by derekkraan** [comment]
https://hex.pm/packages/horde/0.4.0-rc.1
