### ISSUE TITLE
Does Horde move process and state liek swarm

### ISSUE THREAD

**Issue by shifters67** [derekkraan/horde#6]
Apologies for raising an issue as this is more about clarification!

When you gracefully shut a horde node down, the process it has are moved to a new node according to the documentation but does the state of the process also move with it in the same way as swarm does?

thanks

Tom

**Comment by derekkraan** [comment]
No worries. Horde doesn't attempt to move state over to the new node. It only uses the child spec (like a normal supervisor) to restart the process.

You could implement something like what horde has by storing the state somewhere in the terminate callback and rehydrate in the init callback.

**Comment by derekkraan** [comment]
I'm closing the issue but feel free to ask more questions here and I'll respond.
