### ISSUE TITLE
Process redistribution on node join

### ISSUE THREAD

**Issue by beardedeagle** [derekkraan/horde#86]
Creating this issue as a placeholder for the conversation we were having today. The tldr; of that conversation was:
```
dkraan [12:31 PM]
So Horde doesn't do any redistributing when a node joins the cluster, but when a node leaves the cluster its processes will be evenly distributed across the remaining nodes.
```
It would be good if processes in horde could be rebalanced on node up/node join, and not only on node down. The thought so far was that there may be a pluggable way to expose this type of functionality to the library user.

**Comment by beardedeagle** [comment]
If I were to tackle this, do you have an idea of where to start?

**Comment by sikanrong** [comment]
I didn't realize this was an open issue until now - just wanted to chime in and say that I fixed this! This is the [PR](https://github.com/derekkraan/horde/pull/164); if you're interested in using Horde with this feature included, you guys are welcome to use my fork of it until the PR gets merged, or a similar feature is implemented in the original horde repository.

**Comment by sikanrong** [comment]
hey so I just made a massive comment about the proposed (updated) design of this thing: anybody following this ticket may want to look this over and/or comment: https://github.com/derekkraan/horde/pull/164#issuecomment-538033804

**Comment by sikanrong** [comment]
Anybody following this ticket; I just updated the PR - I think this time, I really did finish this!! 🥇wish me luck.

**Comment by derekkraan** [comment]
#164
