### ISSUE TITLE
time out in Horde.Registry.lookup v0.3.0

### ISSUE THREAD

**Issue by uberbrodt** [derekkraan/horde#87]
I'm running a script that is creating a bunch of GenServers registered with Horde.Registry. The script isn't attempting to do anything in parallel, just working through a list one at a time.  Sometimes, after running for a few minutes, I will observe a hang and see the following crash:

```
** (exit) exited in: GenServer.call(MyApp.EntityRegistry, :get_keys_ets_table, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (horde) lib/horde/registry.ex:95: Horde.Registry.lookup/2
    (gambit) lib/my_app/persistence/entity.ex:56: MyApp.Survey.Major.ensure_started/1
    (gambit) lib/my_app/survey/major.ex:4: MyApp.Survey.Major.update/2
    (gambit) lib/my_app/core_sync/import.ex:294: MyApp.CoreSync.Import.save_major_translation/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (gambit) lib/my_app/core_sync/import.ex:70: anonymous fn/2 in MyApp.CoreSync.Import.process_majors/0
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (gambit) lib/my_app/core_sync/import.ex:66: MyApp.CoreSync.Import.process_majors/0
    (gambit) lib/my_app/core_sync/import.ex:15: MyApp.CoreSync.Import.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) lib/code.ex:767: Code.require_file/2
```
Right now I'm testing locally with a single node, so I don't think this is an issue with the CRDT.
Looks like there's been a lot of work done since 0.3.0...what would be your recommendation here? Are the RC releases "safe" to use?

**Comment by derekkraan** [comment]
Hi Chris,

At this point there has been a lot of work that has gone in since 0.3.0. My recommendation would be to try the latest RC. It will at least be free of this bug that you are running into right now.

In terms of overall safety, I am working hard on getting 0.5.0 really ready. The code is good, but I'm still focusing on really getting the performance right before I release 0.5.0.

Hope this answers your question. I'll close this issue since its already been fixed in master, but if you have any more questions feel free to reply in this issue and I'll respond.

Derek

On Fri, Apr 5, 2019, at 18:16, Chris Brodt wrote:
> I'm running a script that is creating a bunch of GenServers registered with Horde.Registry. The script isn't attempting to do anything in parallel, just working through a list one at a time. Sometimes, after running for a few minutes, I will observe a hang and see the following crash:

> `** (exit) exited in: GenServer.call(MyApp.EntityRegistry, :get_keys_ets_table, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (horde) lib/horde/registry.ex:95: Horde.Registry.lookup/2
    (gambit) lib/my_app/persistence/entity.ex:56: MyApp.Survey.Major.ensure_started/1
    (gambit) lib/my_app/survey/major.ex:4: MyApp.Survey.Major.update/2
    (gambit) lib/my_app/core_sync/import.ex:294: MyApp.CoreSync.Import.save_major_translation/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (gambit) lib/my_app/core_sync/import.ex:70: anonymous fn/2 in MyApp.CoreSync.Import.process_majors/0
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (gambit) lib/my_app/core_sync/import.ex:66: MyApp.CoreSync.Import.process_majors/0
    (gambit) lib/my_app/core_sync/import.ex:15: MyApp.CoreSync.Import.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) lib/code.ex:767: Code.require_file/2
`
