### ISSUE TITLE
Incorrect behaviour during netsplits?

### ISSUE THREAD

**Issue by frekw** [derekkraan/horde#91]
See: https://asciinema.org/a/r19vUhFueoPRbf7IaPB92ntpu

I'm starting a two node cluster and then force a net split. During the net split, I am unable to start a second process with the same name (the supervisor won't let me). This means that I cannot have availability on both sides of the split.

However, if I tweak the memberships during the split (which I probably shouldn't be doing), I am able to start the same process on both sides. However, if I then heal the split and update the member list to contain both nodes this conflict is never resolved and I end up with two processes running.

Kind of the same behaviour can be observed when a node shuts down: https://asciinema.org/a/RDS52ntJYw6gCDXLN2rmfYkKc but in this case I lose the process entirely.

In both the cases of a net split, as well as a shutdown (since the scenario is pretty much the same for the other nodes in the cluster) I would have expected the process to be migrated to the other node. Or at least that I would have been able to start it.

I'm not fully sure what the expected behaviour is supposed to be, but I think this may be worth looking into.

**Comment by frekw** [comment]
Oh and also, the source can be found [here](https://github.com/frekw/horde-test).

**Comment by derekkraan** [comment]
Hi, thanks again for the bug report.

This is a tricky situation, because this is not an actual netsplit. In fact, both nodes are still in the cluster, but it may seem temporarily that they are not (if you . So if you send an actual message from one side to the other, you'll notice that it arrives and the cluster recognizes again that it is intact.

If you try `send(v(3), :hello)` in the right pane, you'll see that it succeeds.

I am trying to use `local_cluster` and `schism` to add tests for these scenarios to Horde, so I'll leave this issue open until then.

**Comment by derekkraan** [comment]
I've added an initial test to ensure that the supervisor performs as expected during and after a netsplit. See #93.

**Comment by frekw** [comment]
Hi!

This is indeed a proper netsplit. The way I simulate it is by changing the cookie for one of the nodes and then using `Node.disconnect`; see https://github.com/frekw/horde-test/blob/master/lib/hord_test.ex#L26-L31.

This is usually how I simulate netsplits when writing tests using `local_cluster` as well!

However, I tried this exact test with #92 and then everything seems to be working as expected! 👍 

When testing with #92 I did find another bug more closely related to what you describe, which is that if you change the cluster memberships for _connected_ nodes it will fail to remove/restart processes running on nodes in the previous configuration (but not the new one). Not sure what the proper behaviour under those circumstances should be, but I think they should be treated the same way as a netsplit. Do you want me to file a different bug for that?

And lastly, thanks for all your hard work. This is a great library which fills a big gap in the Erlang/Elixir distribution story!
